import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import URQLProvider from "@/components/providers/urql";
import Toaster from "@/components/atoms/a-toaster";
import JotaiProvider from "@/components/providers/jotai";
import TanstackProvider from "@/components/providers/tanstack-query";

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`${poppins.variable} ${poppins.className} antialiased`}
      >
        <Toaster />
        <JotaiProvider>
          <TanstackProvider>
            <URQLProvider>{children}</URQLProvider>
          </TanstackProvider>
        </JotaiProvider>
      </body>
    </html>
  );
}
